# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NAMtqkfVnGnlxLuHGHy5Lbauj3nvaX6S
"""

import hashlib

senha = "1234"
hash_md5 = hashlib.md5(senha.encode()).hexdigest()
print("hash MD5:",hash_md5)

!pip install bcrypt

import bcrypt

senha = b"1234"

hash_seguro = bcrypt.hashpw(senha, bcrypt.gensalt())
print("Hash seguro",hash_seguro)

"""Exemplos de interação com assistente de IA

1) machine learnign regressivo
"""

from sklearn.linear_model import LinearRegression

x = [[1],[2],[3],[4]] #dado entrado
y = [2,4,6,8] #dado esperado
modelo = LinearRegression()
modelo.fit(x, y) #y =2x
print(modelo.predict([[5]]))

"""IA generativa Engenharia de prompt"""

